#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ejercicio_Hospital")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::WindowsFormsApp1.Properties.Settings.Default.Ejercicio_HospitalConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Enfermo> Enfermo
		{
			get
			{
				return this.GetTable<Enfermo>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarEnfermo")]
		public int SP_EliminarEnfermo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> inscripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inscripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarEnfermo")]
		public int SP_InsertarEnfermo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> inscripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dir", DbType="Int")] System.Nullable<int> dir, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Nac", DbType="SmallDateTime")] System.Nullable<System.DateTime> fecha_Nac, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S", DbType="VarChar(2)")] string s, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NSS", DbType="Int")] System.Nullable<int> nSS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cod_Hospital", DbType="Int")] System.Nullable<int> cod_Hospital)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inscripcion, apellido, direccion, dir, fecha_Nac, s, nSS, cod_Hospital);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_listarEnfermos")]
		public ISingleResult<SP_listarEnfermosResult> SP_listarEnfermos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_listarEnfermosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificarEnfermo")]
		public int SP_ModificarEnfermo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> inscripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dir", DbType="Int")] System.Nullable<int> dir, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Nac", DbType="SmallDateTime")] System.Nullable<System.DateTime> fecha_Nac, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="S", DbType="VarChar(2)")] string s, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NSS", DbType="Int")] System.Nullable<int> nSS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cod_Hospital", DbType="Int")] System.Nullable<int> cod_Hospital)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inscripcion, apellido, direccion, dir, fecha_Nac, s, nSS, cod_Hospital);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Enfermo")]
	public partial class Enfermo
	{
		
		private System.Nullable<int> _inscripcion;
		
		private string _Apellido;
		
		private string _Direccion;
		
		private System.Nullable<int> _Dir;
		
		private System.Nullable<System.DateTime> _Fecha_Nac;
		
		private string _S;
		
		private System.Nullable<int> _NSS;
		
		private System.Nullable<int> _Cod_Hospital;
		
		public Enfermo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inscripcion", DbType="Int")]
		public System.Nullable<int> inscripcion
		{
			get
			{
				return this._inscripcion;
			}
			set
			{
				if ((this._inscripcion != value))
				{
					this._inscripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir", DbType="Int")]
		public System.Nullable<int> Dir
		{
			get
			{
				return this._Dir;
			}
			set
			{
				if ((this._Dir != value))
				{
					this._Dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Nac", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fecha_Nac
		{
			get
			{
				return this._Fecha_Nac;
			}
			set
			{
				if ((this._Fecha_Nac != value))
				{
					this._Fecha_Nac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S", DbType="VarChar(2)")]
		public string S
		{
			get
			{
				return this._S;
			}
			set
			{
				if ((this._S != value))
				{
					this._S = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSS", DbType="Int")]
		public System.Nullable<int> NSS
		{
			get
			{
				return this._NSS;
			}
			set
			{
				if ((this._NSS != value))
				{
					this._NSS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Hospital", DbType="Int")]
		public System.Nullable<int> Cod_Hospital
		{
			get
			{
				return this._Cod_Hospital;
			}
			set
			{
				if ((this._Cod_Hospital != value))
				{
					this._Cod_Hospital = value;
				}
			}
		}
	}
	
	public partial class SP_listarEnfermosResult
	{
		
		private System.Nullable<int> _inscripcion;
		
		private string _Apellido;
		
		private string _Direccion;
		
		private System.Nullable<int> _Dir;
		
		private System.Nullable<System.DateTime> _Fecha_Nac;
		
		private string _S;
		
		private System.Nullable<int> _NSS;
		
		private System.Nullable<int> _Cod_Hospital;
		
		public SP_listarEnfermosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inscripcion", DbType="Int")]
		public System.Nullable<int> inscripcion
		{
			get
			{
				return this._inscripcion;
			}
			set
			{
				if ((this._inscripcion != value))
				{
					this._inscripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir", DbType="Int")]
		public System.Nullable<int> Dir
		{
			get
			{
				return this._Dir;
			}
			set
			{
				if ((this._Dir != value))
				{
					this._Dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Nac", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fecha_Nac
		{
			get
			{
				return this._Fecha_Nac;
			}
			set
			{
				if ((this._Fecha_Nac != value))
				{
					this._Fecha_Nac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S", DbType="VarChar(2)")]
		public string S
		{
			get
			{
				return this._S;
			}
			set
			{
				if ((this._S != value))
				{
					this._S = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSS", DbType="Int")]
		public System.Nullable<int> NSS
		{
			get
			{
				return this._NSS;
			}
			set
			{
				if ((this._NSS != value))
				{
					this._NSS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Hospital", DbType="Int")]
		public System.Nullable<int> Cod_Hospital
		{
			get
			{
				return this._Cod_Hospital;
			}
			set
			{
				if ((this._Cod_Hospital != value))
				{
					this._Cod_Hospital = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
