<?xml version="1.0" encoding="utf-8"?><Database Name="Ejercicio_Hospital" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CADAVILES10\SQLEXPRESS;Initial Catalog=Ejercicio_Hospital;Integrated Security=True" SettingsObjectName="WindowsFormsApp1.Properties.Settings" SettingsPropertyName="Ejercicio_HospitalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Enfermo" Member="Enfermo">
    <Type Name="Enfermo">
      <Column Name="inscripcion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha_Nac" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="S" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="NSS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cod_Hospital" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_EliminarEnfermo" Method="SP_EliminarEnfermo">
    <Parameter Name="inscripcion" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarEnfermo" Method="SP_InsertarEnfermo">
    <Parameter Name="inscripcion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Dir" Parameter="dir" Type="System.Int32" DbType="Int" />
    <Parameter Name="Fecha_Nac" Parameter="fecha_Nac" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="S" Parameter="s" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="NSS" Parameter="nSS" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cod_Hospital" Parameter="cod_Hospital" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_listarEnfermos" Method="SP_listarEnfermos">
    <ElementType Name="SP_listarEnfermosResult">
      <Column Name="inscripcion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha_Nac" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="S" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="NSS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cod_Hospital" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ModificarEnfermo" Method="SP_ModificarEnfermo">
    <Parameter Name="inscripcion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Dir" Parameter="dir" Type="System.Int32" DbType="Int" />
    <Parameter Name="Fecha_Nac" Parameter="fecha_Nac" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="S" Parameter="s" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="NSS" Parameter="nSS" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cod_Hospital" Parameter="cod_Hospital" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>