<?xml version="1.0" encoding="utf-8"?><Database Name="FILTROS" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CADAVILES10\SQLEXPRESS;Initial Catalog=FILTROS;Integrated Security=True" SettingsObjectName="Ejercicio_Filtros.Properties.Settings" SettingsPropertyName="FILTROSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DatosViernes" Member="DatosViernes">
    <Type Name="DatosViernes">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FechaInscripcion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="FechaContratacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Curso" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>